apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-advisor-agent-portfolio
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: investment-advisor-agent-portfolio
  template:
    metadata:
      labels:
        app: investment-advisor-agent-portfolio
    spec:
      containers:
        - name: container
          image: {{ .Values.image.repository }}:{{ .Values.image.tags.portfolio }}
          ports:
            - containerPort: 7002
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /tools
              port: 7002
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: PORT
              value: "7002"
            - name: PYTHONUNBUFFERED
              value: "1"
