apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-advisor-agent-risk
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: investment-advisor-agent-risk
  template:
    metadata:
      labels:
        app: investment-advisor-agent-risk
    spec:
      containers:
        - name: container
          image: {{ .Values.image.repository }}:{{ .Values.image.tags.risk }}
          ports:
            - containerPort: 7001
              protocol: TCP
