apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: container
          image: {{ .Values.image.registry }}/orchestrator:{{ .Values.image.tag }}
          ports:
            - containerPort: 5000
              protocol: TCP
