apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: container
          image: {{ .Values.image.registry }}/ui:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
              protocol: TCP
