apiVersion: apps/v1
kind: Deployment
metadata:
  name: neurosymbolic-ai-portfolio
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: neurosymbolic-ai-portfolio
  template:
    metadata:
      labels:
        app: neurosymbolic-ai-portfolio
    spec:
      containers:
        - name: container
          image: {{ .Values.image.registry }}/neurosymbolic-ai-portfolio:{{ .Values.image.tag }}
          ports:
            - containerPort: 7002
              protocol: TCP
