apiVersion: apps/v1
kind: Deployment
metadata:
  name: neurosymbolic-ai-risk
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: neurosymbolic-ai-risk
  template:
    metadata:
      labels:
        app: neurosymbolic-ai-risk
    spec:
      containers:
        - name: container
          image: {{ .Values.image.registry }}/neurosymbolic-ai-risk:{{ .Values.image.tag }}
          ports:
            - containerPort: 7001
              protocol: TCP
