apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ .Values.namespace }}
  annotations:
    serving.kserve.io/s3-endpoint: minio.{{ .Values.namespace }}.svc.cluster.local:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: us-east-1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.rootUser }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.rootPassword }}
