apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-endpoints
  namespace: neurosymbolic-ai
data:
  GUIDELINES_URL: "http://agentic-ai-guidelines:7003"
  PORTFOLIO_URL: "http://agentic-ai-portfolio:7002"
  RISK_URL: "http://agentic-ai-risk:7001"