apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: neurosymbolic-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: container
          image: quay.io/aric-rosenbaum/neurosymbolic-ai/ui:latest
          ports:
            - containerPort: 8080
              protocol: TCP