apiVersion: apps/v1
kind: Deployment
metadata:
  name: neurosymbolic-ai-risk
  namespace: neurosymbolic-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neurosymbolic-ai-risk
  template:
    metadata:
      labels:
        app: neurosymbolic-ai-risk
    spec:
      containers:
        - name: container
          image: quay.io/aric-rosenbaum/neurosymbolic-ai/neurosymbolic-ai-risk:latest
          ports:
            - containerPort: 7001
              protocol: TCP