apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: agentic-ai-risk
  namespace: neurosymbolic-ai
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 60
      containers:
        - name: container
          image: quay.io/aric-rosenbaum/neurosymbolic-ai/agentic-ai-risk:latest
          ports:
            - containerPort: 7001
              protocol: TCP