apiVersion: v1
kind: Service
metadata:
  name: neurosymbolic-ai-risk
  namespace: neurosymbolic-ai
spec:
  selector:
    app: neurosymbolic-ai-risk
  ports:
    - name: http
      protocol: TCP
      port: 7001
      targetPort: 7001
  type: ClusterIP