namespace: investment-advisor-agent
image:
  repository: quay.io/ikatav/portfolio-manager-agent
  tags:
    ui: ui
    orchestrator: orchestrator
    risk: risk
    portfolio: portfolio
    guidelines: guidelines
    guidelinesModel: guidelines-model
replicas: 1
ui:
  orchestratorUrl: ""
  llm:
    endpoint: ""
    apiToken: ""
    model: ""
serverless:
  enabled: false
  minScale: "0"
  maxScale: "5"
  concurrency: 10
  timeoutSeconds: 60
guidelines:
  inferenceUrl: "http://guidelines-mlp:80"
guardrails:
  enabled: true
minio:
  rootUser: minioadmin
  rootPassword: minioadmin
