namespace: investment-advisor-agent

image:
  repository: quay.io/ikatav/portfolio-manager-agent
  tags:
    ui: ui
    orchestrator: orchestrator
    risk: risk
    portfolio: portfolio
    guidelines: guidelines

replicas: 1

serverless:
  enabled: false
  minScale: "0"
  maxScale: "5"
  concurrency: 10
  timeoutSeconds: 60
